# specify compiler
language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

# maven
install: true
script: mvn clean verify

# cache maven dir for performance
cache:
  directories:
    - $HOME/.m2
