# specify compiler
language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
  - openjdk8

# maven
install: true
script: mvn clean verify

# cache maven dir for performance
cache:
  directories:
    - $HOME/.m2