# specify compiler
language: java
sudo: false # faster builds
jdk: openjdk8

dist: xenial
services:
  - xvfb

# maven
install: true
script:
  - xvfb-run make test
  - mvn clean verify

# cache maven dir for performance
cache:
  directories:
    - $HOME/.m2
